applications: thingy: Disable nRF5340 anomaly workaround for bootloader
Change disables the nRF5340 SoC anomaly 160 workaround in MCUboot
bootloader configuration of Thingy:53. This prevents build failures
caused by undefined reference to `sys_clock_cycle_get_32' in ZRelease
configuration.

Jira: NCSDK-20874

Signed-off-by: Marek Pieta <Marek.Pieta@nordicsemi.no>